### PR TITLE
grunt, bower and bootstrap files

### PR DESCRIPTION
**Pull request by craigdavies7**
READ BEFORE DOING ANYTHING.

Downloaded grunt, bower and bootstrap sass files into the painting folder within 'bootstrapApp' branch. There was an issue with running 'Grunt' command within terminal as it was complaining about the @import “_bootstrap.scss”; command within the app.scss file. See the following link for guide on how this install was created....

http://shermandigital.com/blog/bootstrap-project-with-bower-and-grunt/

I believe if this has worked correctly you simply need to run the 'bower install' command within your terminal.

Seems very over the top though and was wondering whether it is easier to just follow the Grunt installation of bootstrap from the following link?...

http://getbootstrap.com/getting-started/

Let me know what you think?

### CODE REVIEW

**Comment by neilwilliams** [comment]
First things first, you need top ignore the /bower_components directory from git.

So edit your .gitignore file and include /bower_components.

That should reduce the files changed quite a bit.

**Review by nwillia2 — CHANGES_REQUESTED** [review]
The gitignore stuff needs to happen, and the import needs fixing - you accidentally copied some dodgy quotes.

**Comment by neilwilliams** [comment]
I somehow managed to comment as a member of the public...

**Review by neilwilliams — CHANGES_REQUESTED** [review]
Changes required, pr incoming...

**Comment by neilwilliams** [comment]
Added the fixes identified to another PR:
https://github.com/craigdavies7/painting/pull/11

I'll close this one for now, and we'll reopen once your happy with the other one.

**Review by neilwilliams — APPROVED** [review]

**Pull request merged**
